### ISSUE TITLE
Local SSD causes SSH to never become available

### ISSUE THREAD

**Issue by RyanMarcus** [GoogleCloudPlatform/compute-archlinux-image-builder#32]
Hi folks,

Thanks for maintaining the Arch Linux image! I really appreciate it.

I might be doing something wrong, but it seems like creating an instance with a local SSD causes the SSH server to never come online. The "SSH" button on the control panel doesn't ever connect either, and the page to view the serial output just shows an error saying it "failed to load."
```
gcloud compute instances create mymachinename --image-project=arch-linux-gce --image-family=arch --local-ssd interface=nvme
```

... same results using `interface=scsi`.

Thanks,
Ryan

**Comment by lcastelli** [comment]
Sorry for the slow answer. It seems the problem is that, as the hardware configuration changes, the interface name changes as well (because of "predictable interface names"), which causes initialization scripts to fail. I fixed this by disabling predictable interface names at commit 023af32f448c49288d622dd0223d59a3051c1e4f

Please reopen in case that doesn't solve your issues.
