### ISSUE TITLE
How to make the default partition /dev/sda1 instead of /dev/sda2?

### ISSUE THREAD

**Issue by aofei** [GoogleCloudPlatform/compute-archlinux-image-builder#34]
First of all, huge thanks for this project, it really helped me a lot! I love this project! ❤️

However, I found that the default installed system is on the `/dev/sda2` disk partition. Although this is okay, but OCD makes me want to ask if you guys have a way to make the default disk partition `/dev/sda1` instead of `/dev/sda2` when installing the system (or when building the image)?

**Comment by toastwaffle** [comment]
Hey Aofei,

Thank you for your support!

The root partition is `/dev/sda2` because `/dev/sda1` is the [BIOS boot partition](https://en.wikipedia.org/wiki/BIOS_boot_partition) used to support the GRUB bootloader. I believe theoretically the partitions could be reordered by changing [the `sfdisk` command](https://github.com/GoogleCloudPlatform/compute-archlinux-image-builder/blob/023af32f448c49288d622dd0223d59a3051c1e4f/build-arch-gce#L41) in the build script, but there's no good reason to commit such a change to this repository (as I understand it, the convention is to have the boot partition(s) towards the start of the disk).

**Comment by aofei** [comment]
I see, thank you for your reply @toastwaffle! I'll try it in my own fork. 😊

**Comment by lcastelli** [comment]
Note that swapping the order of the partitions will break the auto-resize of the root partition. In particular if you change the disk size to be beyond 10GB, a boot script will detect that and automatically extend the root partition to take the extra available space. This is only possible if the root partition is the last one on the disk.
