### ISSUE TITLE
Cannot provision with docker-machine: hostname command not found

### ISSUE THREAD

**Issue by mpdeimos** [GoogleCloudPlatform/compute-archlinux-image-builder#36]
We're using arch linux in our CI farm since the deprecation of flatcar earlier this year. So far everything was running fine, but starting from today I'm getting the following output whenever a new machine is provisioned via docker-machine: 

> sudo: hostname: command not found

I digged into the code of docker-machie and it looks like it is expecting the hostname binary to be present in order to set the hostname:

https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/blob/master/libmachine/provision/generic.go#L41
~~~
func (provisioner *GenericProvisioner) SetHostname(hostname string) error {
	if _, err := provisioner.SSHCommand(fmt.Sprintf(
		"sudo hostname %s && echo %q | sudo tee /etc/hostname",
		hostname,
		hostname,
	)); err != nil {
		return err
	}
~~~

The binary is however no longer present. I saw that you changed something yesterday on master which might have triggered an image rebuild. Are you aware of a change so that inetutils (the package that provides hostname) is now no longer present in the base install? (Sidemark: the laptop I've set up last week does not have it installed either)

I think the issue needs ultimately fixed in docker-machine, but the project is in maintenance mode. Hence, I'm wondering whether inetutils should be included in this image?

Second: Do you provide "old" arch linux images, e.g. the one that was still present on GCP yesterday?

**Comment by lcastelli** [comment]
Inetutils is indeed not part of the Arch Linux base installation. It did end up in our images because it was brought in as dependency of the GCE guest tools. That dependency is now gone after an upstream update, and this is probably what triggered your breakage. See https://aur.archlinux.org/cgit/aur.git/commit/?h=google-compute-engine&id=79d690cda0df0013e9379bef9b85100d47fe962e

My recommendation is to have a setup script where you explicitly install all packages you need. Alternatively you can customize the Arch image, either by taking our pre-built images, adding additional packages, and building a new image out of that, or by customizing the build script and creating new images from scratch.

We do keep previous images around for ~1 year. You should be able to list them with:
`gcloud compute images list --project=arch-linux-gce --no-standard-images`

For the record the previous one was 'arch-v20200516'.

**Comment by mpdeimos** [comment]
Thanks for clarification. It perfectly makes sense to not put inetutils in the default image.

> My recommendation is to have a setup script where you explicitly install all packages you need

In case of docker-mache (in conjunction with a GitLab CI autoscaling runner) that's sadly not possible. You're only given with the option to set a GCE image and docker-machine will do the remaining provisioning. Still, I think it makes sense to raise the issue at docker-machine directly. It should be easy to either install inetutils or use `hostnamectl` instead, so will create a PR there...

In the meantime I'll figure out how to build a custom image out of yours.

> We do keep previous images around for ~1 year. You should be able to list them with:

I've already tried `gcloud compute images list --project=arch-linux-gce --no-standard-images`, but getting the following error. This is why I've asked regarding the older version.

`Required 'compute.images.list' permission for 'projects/arch-linux-gce'`
